homeassistant: true

# allow new devices to join
permit_join: true

mqtt:
  base_topic: homeassistant/zigbee
  server: 'mqtt://192.168.1.200:1883'
  # user: your_user
  # password: your_password

serial:
  port: /dev/ttyUSB0
  adapter: ember             # or ember, depending on your Z2M version/firmware
  rtscts: true              # recommended for ZBT-1 

frontend:
  port: 8080

