homeassistant: true

mqtt:
  base_topic: homeassistant-zigbee
  server: 'mqtt://dump.local:1883'
  # user: your_user
  # password: your_password

serial:
  port: /dev/ttyUSB0

frontend:
  port: 8080

