version: '2.4'

services:
  zigbee2mqtt:
    build: .
    restart: unless-stopped
    # volumes:
      # - z2m-data:/app/data        # named volume managed by balena, not a bind mount
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - TZ=America/Chicago

# volumes:
#   z2m-data:
